03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/ManageOrder.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TasteRestaurant.Data;
using TasteRestaurant.Pages.ViewModels;
using TasteRestaurant.Utility;

namespace TasteRestaurant.Pages.Order
{
    [Authorize]
    public class ManageOrderModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public ManageOrderModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public List<OrderTotalDetails> orderTotalDetails { get; set; }

        public async Task<IActionResult> OnGet()
        {
            orderTotalDetails = new List<OrderTotalDetails>();

            ClaimsIdentity claimIdentity = (ClaimsIdentity)this.User.Identity;

            Claim claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            string userId = claim.Value;

            var orderHeaderList = await _db.OrderHeader
                .Where(od => od.UserId == userId)
                .Where(odl => odl.Status == SD.StatusSubmited || odl.Status == SD.StatusPreparing)
                .OrderByDescending(hl => hl.OrderDate)
                .ToListAsync();

            foreach (var oh in orderHeaderList)
            {
                List<OrderDetails> orderDetails = _db.OrderDetails
                    .Where(od => od.OrderId == oh.Id)
                    .ToList();

                orderTotalDetails.Add(new OrderTotalDetails() { orderDetailsList = orderDetails, orderHeader = oh });
            }
            
            return Page();
        }

        public async Task<IActionResult> OnGetChangeOrderStatus(int? headerId ) 
        {     
            if (headerId == null)
            {
                return NotFound();
            }

            var currentOrderHeader = await _db.OrderHeader.SingleOrDefaultAsync(oh => oh.Id == headerId);

            switch (currentOrderHeader.Status)
            {
                case SD.StatusSubmited:
                    currentOrderHeader.Status = SD.StatusPreparing;
                    break;

                case SD.StatusPreparing:
                    currentOrderHeader.Status = SD.StatusPickUpReady;
                    break;

                case SD.StatusPickUpReady:
                    currentOrderHeader.Status = SD.StatusCompleted;
                    break;
                    
                default:
                    break;
            }

            _db.OrderHeader.Update(currentOrderHeader);

            await _db.SaveChangesAsync();

            return RedirectToPage(SD.ManageOrder);
        }

        public async Task<IActionResult> OnGetCancelOrder(int? headerId)
        {
            if (headerId == null){
                return NotFound();
            }

            var currentOrderHeader = await _db.OrderHeader.SingleOrDefaultAsync(oh => oh.Id == headerId);

            currentOrderHeader.Status = SD.StatusCancelled;
            
            _db.OrderHeader.Update(currentOrderHeader);

            await _db.SaveChangesAsync();

            return RedirectToPage(SD.ManageOrder);
        }
    }
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderConfirmation.cshtml.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TasteRestaurant.Data;
using TasteRestaurant.Pages.ViewModels;

namespace TasteRestaurant.Pages.Order
{
    [Authorize]
    public class OrderConfirmationModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public OrderConfirmationModel(ApplicationDbContext db)
        {
            _db = db;
            OrderDetailsTotal = new OrderTotalDetails();
        }

        public OrderTotalDetails OrderDetailsTotal { get; set; }
        
        public async Task<IActionResult> OnGet(int? orderId)
        {
            if (orderId == null) {
                return NotFound();
            }

            ClaimsIdentity claimIdentity = (ClaimsIdentity)this.User.Identity;

            Claim claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            string userId = claim.Value;

            this.OrderDetailsTotal.orderHeader = await _db.OrderHeader
                .SingleOrDefaultAsync(o => o.Id == orderId && o.UserId == userId);

            if (OrderDetailsTotal.orderHeader == null){
                return NotFound();
            }

            OrderDetailsTotal.orderDetailsList = 
                _db.OrderDetails.Where(od => od.OrderId == orderId).ToList();
            
            return Page();
        }
    }
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderHistory.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TasteRestaurant.Data;
using TasteRestaurant.Pages.ViewModels;

namespace TasteRestaurant.Pages.Order
{
    public class OrderHistoryModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public OrderHistoryModel(ApplicationDbContext db)
        {
            _db = db;
            orderTotalDetails = new List<OrderTotalDetails>();
        }

        public List<OrderTotalDetails> orderTotalDetails { get; set; }

        public bool Loaded { get; set; }

        public async Task<IActionResult> OnGet(int num=0)
        {
            ClaimsIdentity claimIdentity = (ClaimsIdentity)this.User.Identity;

            Claim claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            string userId = claim.Value;

            var orderHeaderList = await _db.OrderHeader
                .Where(od => od.UserId == userId)
                .OrderByDescending(hl => hl.OrderDate)
                .ToListAsync();
            
            foreach (var oh in orderHeaderList)
            {
                List<OrderDetails> orderDetails = _db.OrderDetails
                    .Where(od => od.OrderId == oh.Id)
                    .ToList();

                orderTotalDetails.Add(new OrderTotalDetails() {orderDetailsList = orderDetails, orderHeader = oh });
            }

            if (num == 0)
            {
                orderTotalDetails = orderTotalDetails.Take(5).ToList();
                Loaded = false;
            }
            else {
                Loaded = true;
            }

            return Page();
        }
    }
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderPickup.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TasteRestaurant.Data;
using TasteRestaurant.Pages.ViewModels;
using TasteRestaurant.Utility;

namespace TasteRestaurant.Pages.Order
{
    public class OrderPickupModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public OrderPickupModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public List<OrderTotalDetails> orderTotalDetails { get; set; }

        [BindProperty]
        public SearchTypeViewModel searchTypeViewModel { get; set; }

        public async Task<IActionResult> OnGet()
        {
            orderTotalDetails = new List<OrderTotalDetails>();

            searchTypeViewModel = new SearchTypeViewModel();

            ClaimsIdentity claimIdentity = (ClaimsIdentity)this.User.Identity;

            Claim claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            string userId = claim.Value;

            var orderHeaderList = await _db.OrderHeader
                .Where(odl => odl.Status == SD.StatusPickUpReady)
                .OrderByDescending(hl => hl.OrderDate)
                .ToListAsync();

            foreach (var oh in orderHeaderList)
            {
                List<OrderDetails> orderDetails = _db.OrderDetails
                    .Where(od => od.OrderId == oh.Id)
                    .ToList();

                orderTotalDetails.Add(new OrderTotalDetails() { orderDetailsList = orderDetails, orderHeader = oh });
            }

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (searchTypeViewModel.SearchCriteria != null)
            {
                if (searchTypeViewModel.SearchText == null)
                    searchTypeViewModel.SearchText = "";

                switch (searchTypeViewModel.SearchCriteria)
                {
                    case SD.Name:

                        var currentUserByName = new ApplicationUser();

                        var allUsers = _db.Users.ToList();
                        foreach (var user in allUsers)
                        {
                            var appUser = (ApplicationUser)user;

                            if (appUser.FullName == searchTypeViewModel.SearchText)
                            {
                                currentUserByName = appUser;
                            }
                        }

                        if (currentUserByName != new ApplicationUser())
                        {
                            //user found list all his orders

                            var orderHeaderListName = await _db.OrderHeader
                                .Where(od => od.UserId == currentUserByName.Id)
                                .OrderByDescending(hl => hl.OrderDate)
                                .ToListAsync();

                            foreach (var oh in orderHeaderListName)
                            {
                                List<OrderDetails> orderDetails = _db.OrderDetails
                                    .Where(od => od.OrderId == oh.Id)
                                    .ToList();

                                orderTotalDetails.Add(new OrderTotalDetails() { orderDetailsList = orderDetails, orderHeader = oh });
                            }
                        }
                        else
                        {
                            // user not found
                            return Page();
                        }

                        break;

                    case SD.Email:

                        var userByEmail = await _db.Users
                            .SingleOrDefaultAsync(u => u.Email == searchTypeViewModel.SearchText);

                        if (userByEmail == null)
                        {

                            return Page();
                        }
                        else {

                            var orderHeaderListEmail = await _db.OrderHeader
                             .Where(odl => odl.UserId == userByEmail.Id)
                             .OrderByDescending(hl => hl.OrderDate)
                             .ToListAsync();

                            foreach (var oh in orderHeaderListEmail)
                            {
                                List<OrderDetails> orderDetails = _db.OrderDetails
                                    .Where(od => od.OrderId == oh.Id)
                                    .ToList();

                                orderTotalDetails.Add(new OrderTotalDetails() { orderDetailsList = orderDetails, orderHeader = oh });
                            }
                        }

                        break;

                    case SD.Phone:

                        var userByPhone = await _db.Users
                            .SingleOrDefaultAsync(u => u.Email == searchTypeViewModel.SearchText);

                        if (userByPhone == null)
                        {

                            return Page();
                        }
                        else
                        {
                            var orderHeaderListPhone = await _db.OrderHeader
                            .Where(odl => odl.UserId == userByPhone.Id)
                            .OrderByDescending(hl => hl.OrderDate)
                            .ToListAsync();

                            foreach (var oh in orderHeaderListPhone)
                            {
                                List<OrderDetails> orderDetails = _db.OrderDetails
                                    .Where(od => od.OrderId == oh.Id)
                                    .ToList();

                                orderTotalDetails.Add(new OrderTotalDetails() { orderDetailsList = orderDetails, orderHeader = oh });
                            }
                        }

                        break;

                    case SD.OrderNumber:


                        int number = -1;

                        try
                        {
                            number = int.Parse(searchTypeViewModel.SearchText);

                            var orderHeaderOrderNumber = await _db.OrderHeader
                                .SingleOrDefaultAsync(odl => odl.Id == number);
                             
                            List<OrderDetails> orderDetails = _db.OrderDetails
                                .Where(od => od.OrderId == orderHeaderOrderNumber.Id)
                                .ToList();
                             
                            orderTotalDetails.Add(new OrderTotalDetails() { orderDetailsList = orderDetails, orderHeader = orderHeaderOrderNumber });
                        }
                        catch
                        {
                        }


                        break;

                    default:
                        break;
                }
            }
            else
            {
                var orderHeaderList = await _db.OrderHeader
                          .Where(odl => odl.Status == SD.StatusPickUpReady)
                          .OrderByDescending(hl => hl.OrderDate)
                          .ToListAsync();

                foreach (var oh in orderHeaderList)
                {
                    List<OrderDetails> orderDetails = _db.OrderDetails
                        .Where(od => od.OrderId == oh.Id)
                        .ToList();

                    orderTotalDetails.Add(new OrderTotalDetails() { orderDetailsList = orderDetails, orderHeader = oh });
                }
            }

            return Page();
        }


    }
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderPickupDetails.cshtml.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TasteRestaurant.Data;
using TasteRestaurant.Pages.ViewModels;
using TasteRestaurant.Utility;

namespace TasteRestaurant.Pages.Order
{
    public class OrderPickupDetailsModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public OrderPickupDetailsModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public OrderTotalDetails OrderDetailsTotal { get; set; }

        public async Task<IActionResult> OnGet(int? orderId)
        {
            OrderDetailsTotal = new OrderTotalDetails();

            if (orderId == null)
            {
                return NotFound();
            }

            ClaimsIdentity claimIdentity = (ClaimsIdentity)this.User.Identity;

            Claim claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            string userId = claim.Value;

            this.OrderDetailsTotal.orderHeader = await _db.OrderHeader
                .Include(oh => oh.User)
                .SingleOrDefaultAsync(o => o.Id == orderId);

            if (OrderDetailsTotal.orderHeader == null)
            {
                return NotFound();
            }

            OrderDetailsTotal.orderDetailsList =_db.OrderDetails
                .Include(od => od.MenuItem)
                .ThenInclude(mi => mi.CategoryType)
                .Include(od => od.MenuItem)
                .ThenInclude(mi => mi.FoodType)
                .Where(od => od.OrderId == orderId).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPost(int? orderId) {

            if (orderId == null)
            {
                return NotFound();
            }

            var currentOrderHeader = await _db.OrderHeader.SingleOrDefaultAsync(oh => oh.Id == orderId);

            currentOrderHeader.Status = SD.StatusCompleted;

            _db.OrderHeader.Update(currentOrderHeader);
            await _db.SaveChangesAsync();

            return RedirectToPage(SD.ManageOrder);
        }
    }
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/ManageOrder.cshtml
@page
@model TasteRestaurant.Pages.Order.ManageOrderModel
@{
    ViewData["Title"] = "ManageOrder";
}

<h2>Manage Order's</h2>

<br />

@foreach (var item in Model.orderTotalDetails)
{
<div class="row form-border">
    <div class="col-sm-5">
        Order Number : @item.orderHeader.Id
        <ul>
            @foreach (var od in item.orderDetailsList)
            {
                <li>@(od.Name) x @(od.Count)</li>
            }
        </ul>
    </div>

    <div class="col-sm-5">
        <div class="col-sm-4 col-sm-offset-2">
            Order Total:
            PickUp Time:
            Order Status:
            Comments:
        </div>
        <div class="col-sm-6">
            <div>@item.orderHeader.OrderTotal</div>
            <div>@item.orderHeader.PickUpTime</div>
            <div>@item.orderHeader.Status</div>
            <div>@item.orderHeader.Comments</div>
        </div>
    </div>

    <div class="col-sm-2">
        @if (item.orderHeader.Status == "Submited")
        {
            <a style="width:100%" asp-page-handler="ChangeOrderStatus" asp-route-headerId="@item.orderHeader.Id" class="btn btn-primary"><i class="fas fa-check"></i> Start Cooking</a>
        }
        else if (item.orderHeader.Status == "Being Prepared")
        {
            <a style="width:100%" asp-page-handler="ChangeOrderStatus" asp-route-headerId="@item.orderHeader.Id" class="btn btn-success"><i class="fas fa-utensils"></i> Order Prepared</a>
        }
        <a style="width:100%" asp-page-handler="CancelOrder" asp-route-headerId="@item.orderHeader.Id" class="btn btn-danger"><i class="fas fa-times"></i> Cancel Order</a>
    </div>


</div>
    
    <br />
}

@if (Model.orderTotalDetails.Count < 1)
{
    <p>No current orders...</p>
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderConfirmation.cshtml
@page
@model TasteRestaurant.Pages.Order.OrderConfirmationModel
@{
    ViewData["Title"] = "OrderConfirmation";
}

<h2>Order Confirmation Page</h2>

<br/>

<partial name="_OrderPartial" model="@Model.OrderDetailsTotal"/>

<br/>

<a href="/Cart/Index" class="btn btn-success">Place Another Order</a>

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderHistory.cshtml
@page
@model TasteRestaurant.Pages.Order.OrderHistoryModel
@{
    ViewData["Title"] = "OrderHistory";
}

<h2>Order History</h2>

<br/>



@if (Model.orderTotalDetails.Count == 5 && !Model.Loaded) { 
    <a asp-page="OrderHistory" asp-route-num="1" class="btn btn-success">Load All Orders...</a>
}

<br />
<br />

@foreach (var item in Model.orderTotalDetails)
{
    <partial name="_OrderPartial" model="@item" />

    <br />
}

@if (Model.orderTotalDetails.Count < 1)
{
    <p>No past orders...</p>
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderPickup.cshtml
@page
@model TasteRestaurant.Pages.Order.OrderPickupModel
@{
    ViewData["Title"] = "OrderPickup";
}

<h2>Order Pickup</h2>

<br />

<div class="col-sm-12">

    <div class="col-sm-4 col-sm-offset-8">

        <form method="post">
            <div class="row">
                <div class="pull-right">
                    <label class="radio-inline">
                        @Html.RadioButtonFor(m => m.searchTypeViewModel.SearchCriteria, "Name")
                        Name&nbsp;
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(m => m.searchTypeViewModel.SearchCriteria, "Email")
                        Email&nbsp;
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(m => m.searchTypeViewModel.SearchCriteria, "Phone")
                        Phone&nbsp;
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(m => m.searchTypeViewModel.SearchCriteria, "OrderNumber")
                        Order No.&nbsp;
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="pull-right">
                    <input style="width:65%" asp-for="@Model.searchTypeViewModel.SearchText" type="text" class="col-sm-8 form-control" />
                    <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i> Search</button>
                </div>
            </div>

        </form>

    </div>


    <br />
    <br />
    <br />
    <hr />
    <br />


    @foreach (var item in Model.orderTotalDetails)
    {
        <div class="row form-border">
            <div class="col-sm-5">
                Order Number : @item.orderHeader.Id
                <ul>
                    @foreach (var od in item.orderDetailsList)
                    {
                        <li>@(od.Name) x @(od.Count)</li>
                    }
                </ul>
            </div>

            <div class="col-sm-5">
                <div class="col-sm-4 col-sm-offset-2">
                    Order Total:
                    PickUp Time:
                    Order Status:
                    Comments:
                </div>
                <div class="col-sm-6">
                    <div>@item.orderHeader.OrderTotal</div>
                    <div>@item.orderHeader.PickUpTime</div>
                    <div>@item.orderHeader.Status</div>
                    <div>@item.orderHeader.Comments</div>
                </div>
            </div>

            <div class="col-sm-2">
                @if (item.orderHeader.Status == "Ready for Pickup")
                {
                    <a asp-page="OrderPickUpDetails" asp-route-orderId="@item.orderHeader.Id" class="btn btn-success"><i class="fas fa-book"></i> Pick Up Details</a>
                }
                else if (item.orderHeader.Status == "Completed")
                {
                    <button class="btn btn-primary" disabled>Completed</button>
                }
                else if (item.orderHeader.Status == "Submited")
                {
                    <button class="btn btn-primary" disabled>Submitted</button>
                }
                else if (item.orderHeader.Status == "Cancelled")
                {
                    <button class="btn btn-danger" disabled>Cancelled</button>
                }
            </div>

        </div>

        <br />
    }

    @if (Model.orderTotalDetails.Count < 1)
    {
        <p>No orders found...</p>
        <br/>
    }

</div>

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Order/OrderPickupDetails.cshtml
@page
@model TasteRestaurant.Pages.Order.OrderPickupDetailsModel
@{
    ViewData["Title"] = "OrderPickupDetails";
}


<h2>Confirm Pickup Details : </h2>

<br/>

<style>

    .form-border-details {
        border: 1px solid #bbb9b9;
        padding: 20px;
    }

    .item-count {
        border:1px solid grey; 
        background-color:grey; 
        border-radius:100%; 
        padding:1px 2px 0px 2px; 
        color:white;
    }

</style>

<div class="row form-border-details">

    <form method="post">
        <div class="col-sm-8" style="border-right:1px solid #bbb9b9;">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="@Model.OrderDetailsTotal.orderHeader.User.FullName"></label>
                </div>
                <div class="col-sm-8 col-sm-offset-2">
                    <input asp-for="@Model.OrderDetailsTotal.orderHeader.User.FullName" disabled class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="@Model.OrderDetailsTotal.orderHeader.User.Email"></label>
                </div>
                <div class="col-sm-8 col-sm-offset-2">
                    <input asp-for="@Model.OrderDetailsTotal.orderHeader.User.Email" disabled class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="@Model.OrderDetailsTotal.orderHeader.User.PhoneNumber"></label>
                </div>
                <div class="col-sm-8 col-sm-offset-2">
                    <input asp-for="@Model.OrderDetailsTotal.orderHeader.User.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="@Model.OrderDetailsTotal.orderHeader.OrderTotal"></label>
                </div>
                <div class="col-sm-8 col-sm-offset-2">
                    <input asp-for="@Model.OrderDetailsTotal.orderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="@Model.OrderDetailsTotal.orderHeader.OrderDate"></label>
                </div>
                <div class="col-sm-8 col-sm-offset-2">
                    <input asp-for="@Model.OrderDetailsTotal.orderHeader.OrderDate" disabled class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="@Model.OrderDetailsTotal.orderHeader.Comments"></label>
                </div>
                <div class="col-sm-8 col-sm-offset-2">
                    <input asp-for="@Model.OrderDetailsTotal.orderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>
        <div class="col-sm-4 pull-right">
            
            <p style="margin-top:15px;" >Order No : @Model.OrderDetailsTotal.orderHeader.Id</p>
            <div style="margin-left:15px;">

                <ul class="list-group">
                    @foreach (var item in Model.OrderDetailsTotal.orderDetailsList)
                    {
                        <li class="list-group-item">
                            @item.MenuItem.Name
                            <span class="badge">
                                @item.Count
                            </span>
                        </li>
                    }
                </ul>

            </div>

            <br/>

            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Confirm PickUp</button>

        </div>
    </form>
</div>