03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Cart/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TasteRestaurant.Data;
using TasteRestaurant.Pages.ViewModels;
using TasteRestaurant.Utility;

namespace TasteRestaurant.Pages.Cart
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        
        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public OrderDetailsCart orderDetailsCart { get; set; }
        
        public async Task<IActionResult> OnGet()
        {
            //Initialize OrderDetailsCart
            orderDetailsCart = new OrderDetailsCart();
            orderDetailsCart.OrderHeader = new OrderHeader();
            orderDetailsCart.OrderHeader.OrderTotal = 0;

            //get user ID
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)this.User.Identity;

            Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            string userId = claim.Value;

            var shoppingCart = _db.ShoppingCart.Where(c => c.ApplicationUserId == userId);

            if (shoppingCart == null) {
                return NotFound();
            }

            double totalPrice = 0;

            foreach (var shc in shoppingCart)
            {
                MenuItem currentMenuItem = await _db.MenuItems
                    .SingleOrDefaultAsync(mi => mi.Id == shc.MenuItemId);

                shc.MenuItem = currentMenuItem;
                totalPrice += (shc.MenuItem.Price * shc.Count);

                //Description up to 100 characters
                shc.MenuItem.Description = shc.MenuItem.Description.Substring(0, Math.Min(100, shc.MenuItem.Description.Length)) + ". . .";
            }

            //Set values to the OrderDetailsCart
            this.orderDetailsCart.ShoppingCart = shoppingCart.ToList();

            orderDetailsCart.OrderHeader.OrderTotal = totalPrice;
            orderDetailsCart.OrderHeader.OrderTotal = totalPrice;
            orderDetailsCart.OrderHeader.UserId = userId;
            orderDetailsCart.OrderHeader.User = (ApplicationUser)await _db.Users.SingleOrDefaultAsync(u => u.Id == userId);


            //Timing
            return Page();
        }

        public async Task<IActionResult> OnPost() {
            
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)this.User.Identity;
            Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string userId = claim.Value;

            orderDetailsCart.OrderHeader.UserId = userId;
            orderDetailsCart.OrderHeader.User = (ApplicationUser)await _db.Users.SingleOrDefaultAsync(u => u.Id == userId);


            var shoppingCart = _db.ShoppingCart.Where(c => c.ApplicationUserId == userId);

            if (shoppingCart == null)
            {
                return NotFound();
            }

            double totalPrice = 0;

            foreach (var shc in shoppingCart)
            {
                MenuItem currentMenuItem = await _db.MenuItems
                    .SingleOrDefaultAsync(mi => mi.Id == shc.MenuItemId);

                shc.MenuItem = currentMenuItem;
                totalPrice += (shc.MenuItem.Price * shc.Count);
            }

            this.orderDetailsCart.ShoppingCart = shoppingCart.ToList();
            
            orderDetailsCart.OrderHeader.OrderDate = DateTime.Now;
            orderDetailsCart.OrderHeader.Status = SD.StatusSubmited;

            OrderHeader orderHeader = orderDetailsCart.OrderHeader;

            await _db.OrderHeader.AddAsync(orderHeader);
            await _db.SaveChangesAsync();


            //Order Details
            foreach (var item in orderDetailsCart.ShoppingCart)
            {
                item.MenuItem = await _db.MenuItems.SingleOrDefaultAsync(mi => mi.Id == item.MenuItemId);

                OrderHeader orderHeaderFromDb = await _db.OrderHeader.SingleOrDefaultAsync(sh => sh.Id == orderHeader.Id);
                
                //Save Order In DB
                OrderDetails orderDetails = new OrderDetails()
                {
                    Count = item.Count,
                    Description = item.MenuItem.Description,
                    MenuItem = item.MenuItem,
                    MenuItemId = item.MenuItemId,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.Price,
                    Order = orderHeaderFromDb,
                    OrderId = orderHeaderFromDb.Id
                };

                await _db.OrderDetails.AddAsync(orderDetails);
                await _db.SaveChangesAsync();
            }
            
            //Empty Shopping Cart
            List<ShoppingCart> shoppingCartCurrentUser = await _db.ShoppingCart.Where(sh => sh.ApplicationUserId == userId).ToListAsync();
            
            _db.ShoppingCart.RemoveRange(shoppingCartCurrentUser);

            await _db.SaveChangesAsync();
            
            HttpContext.Session.SetInt32(SD.CartCount, 0);

            string url = Url.Page("/Order/OrderConfirmation", new { orderId = orderHeader.Id });
            return LocalRedirect(url);
        }

        public async Task<IActionResult> OnGetIncreaseCount(int? cartId) {

            ShoppingCart cart = await _db.ShoppingCart.SingleOrDefaultAsync(c => c.Id == cartId);

            cart.Count++;

            await _db.SaveChangesAsync();
            
            return RedirectToPage(SD.Index);
        }

        public async Task<IActionResult> OnGetDecreaseCount(int? cartId)
        {
            ShoppingCart cart = await _db.ShoppingCart.SingleOrDefaultAsync(c => c.Id == cartId);

            cart.Count--;

            if (cart.Count < 1) {
                _db.ShoppingCart.Remove(cart);
                int cartCount = (int)HttpContext.Session.GetInt32("CartCount");

                //reset the session
                cartCount = cartCount - 1;
                HttpContext.Session.SetInt32("CartCount", (int)cartCount);
            }

            await _db.SaveChangesAsync();

            return RedirectToPage(SD.Index);
        }
    }
}

03.Taste Restaurant/TasteRestaurant/TasteRestaurant/Pages/Cart/Index.cshtml
@page
@model TasteRestaurant.Pages.Cart.IndexModel
@using System.Globalization;
    
@{
    ViewData["Title"] = "Index";
}


<h2>Your Shopping Cart</h2>

<form method="post">


<br />

@if (Model.orderDetailsCart.ShoppingCart.Count < 1)
{

    <p>No items added to the shopping cart...</p>
    <br/>
    <a href="/" class="btn btn-success">Add Items</a>

}
else
{

    <div class="thumbnail row">
        <table width="100%">
            <tr class="paddingB30pxToTH">
                <th></th>
                <th style="width:70px; text-align:center;">
                    <label asp-for="@Model.orderDetailsCart.ShoppingCart.FirstOrDefault().MenuItem.Price"></label>
                </th>
                <th style="width:70px; text-align:center;">
                    <label asp-for="@Model.orderDetailsCart.ShoppingCart.FirstOrDefault().Count"></label>
                </th>
                <th></th>
            </tr>

            @foreach (var shopItem in Model.orderDetailsCart.ShoppingCart.Where(sc => sc.Count > 0))
            {
                <tr style="border-bottom:1px solid #e904e4"></tr>
                <tr class="paddingB30pxToTD">
                    <td>
                        <b>@Html.DisplayFor(c => shopItem.MenuItem.Name)</b>
                        <br />
                        @Html.DisplayFor(c => shopItem.MenuItem.Description)
                    </td>
                    <td style="width:70px; text-align:center;">
                        @Html.DisplayFor(c => shopItem.MenuItem.Price)
                    </td>
                    <td style="width:70px; text-align:center;">
                        @Html.DisplayFor(c => shopItem.Count)
                    </td>
                    <td>
                        <a asp-page-handler="IncreaseCount" asp-route-cartId="@shopItem.Id" class="btn btn-primary"><i class="fas fa-plus"></i></a>
                        <a asp-page-handler="DecreaseCount" asp-route-cartId="@shopItem.Id" class="btn btn-danger"><i class="fas fa-minus"></i></a>
                    </td>
                </tr>
            }
        </table>

        <hr />

        <input type="hidden"/>

        <div class="row">
            <div class="col-sm-2">
                <label class="custom-label">Order Total : </label>
            </div>
            <div class="col-sm-3">
                <input asp-for="@Model.orderDetailsCart.OrderHeader.OrderTotal" hidden />
                <input value="@Model.orderDetailsCart.OrderHeader.OrderTotal" disabled class="form-control" />
            </div>
            <div class="col-sm-2 col-sm-offset-2">
                <label class="custom-label">Pick Up Time : </label>
            </div>
            <div class="col-sm-3">
                <input asp-for="@Model.orderDetailsCart.OrderHeader.PickUpTime" type="text" id="timePicker" value="" class="form-control" />
            </div>
        </div>
        
        <br/>

        <div class="row">
            <div class="col-sm-2">
                <label class="custom-label">Comments : </label>
            </div>
            <div class="col-sm-10">
                <textarea asp-for="@Model.orderDetailsCart.OrderHeader.Comments" rows="5" class="form-control"></textarea>
            </div>
        </div>

        <br/>

        <div class="row">
            <div class="col-sm-3 col-sm-offset-2">
                <label id="restaurantCloseLabel" hidden class="text-danger">Restaurant is closed for the day !</label>
            </div>
            <div class="col-sm-7" style="text-align:right;">
                <button type="submit" id="placeOrderButton" class="btn btn-success">Place Order</button>
            </div>
        </div>
    </div>
    
}

</form>



@section Scripts {
    <script type="text/javascript">
        $(document).ready(() => {

            var currentDT = new Date();
            
            var minTime = "";

            if (currentDT.getHours() < 11) {
                minTime = "12:00pm"
            }
            else {
                if (currentDT.getMinutes() < 30) {
                    minTime = (currentDT.getHours() + 1).toString() + ':30pm';
                }
                else { 
                    minTime = (currentDT.getHours() + 2).toString() + ':00pm';
                }
            }
            
            if (currentDT.getHours() > 20) {
                $("#timePicker").prop("disabled", true);
                $("#placeOrderButton").prop("disabled", true);
                $("#restaurantCloseLabel").prop("hidden", false);    
            }
            
            $("#timePicker").timepicker({
                'minTime': minTime,
                'maxTime': '10:00pm'
            });
            
        });
    </script>
}